# Generated by Django 5.1.6 on 2025-03-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0003_recommandation_employe"),
    ]

    operations = [
        migrations.RemoveField(model_name="recommandation", name="employe",),
    ]
