# Generated by Django 5.1.6 on 2025-03-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0004_remove_recommandation_employe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommandation",
            name="employe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employe",
                to="conges.employe",
            ),
            preserve_default=False,
        ),
    ]
