# Generated by Django 5.1.6 on 2025-02-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0004_alter_user_options_user_date_joined_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_employe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
