# Generated by Django 5.1.6 on 2025-02-12 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0005_alter_employe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_employe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
