# Generated by Django 5.1.6 on 2025-03-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0005_recommandation_employe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommandation",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommandations_employe",
                to="conges.employe",
            ),
        ),
    ]
