# Generated by Django 5.1.6 on 2025-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0006_alter_employe_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="demandeconge", name="motif",),
        migrations.AddField(
            model_name="demandeconge",
            name="type_conge",
            field=models.CharField(
                choices=[
                    ("maternite", "Congé de maternité"),
                    ("maladie", "Congé de maladie"),
                    ("paye", "Congé payé"),
                    ("paternite", "Congé de paternité"),
                    ("occasionnel", "Congé occasionnel"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
