# Generated by Django 5.1.6 on 2025-04-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0006_alter_recommandation_employe"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeconge",
            name="charge_de_travail",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="demandeconge",
            name="priorite_de_conge",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="demandeconge",
            name="solde_restant_de_conges",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employe",
            name="taux_absenteisme",
            field=models.FloatField(default=0.0),
        ),
    ]
