# Generated by Django 5.1.6 on 2025-02-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0007_remove_demandeconge_motif_demandeconge_type_conge"),
    ]

    operations = [
        migrations.RemoveField(model_name="demandeconge", name="responsable",),
    ]
