# Generated by Django 5.1.6 on 2025-04-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0007_demandeconge_charge_de_travail_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="demandeconge", name="charge_de_travail",),
        migrations.RemoveField(model_name="demandeconge", name="priorite_de_conge",),
        migrations.RemoveField(
            model_name="demandeconge", name="solde_restant_de_conges",
        ),
        migrations.RemoveField(model_name="employe", name="taux_absenteisme",),
    ]
