# Generated by Django 5.1.6 on 2025-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0008_remove_demandeconge_charge_de_travail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeconge",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="certificat/"),
        ),
    ]
