# Generated by Django 5.1.6 on 2025-02-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0008_remove_demandeconge_responsable"),
    ]

    operations = [
        migrations.DeleteModel(name="Responsable",),
    ]
