# Generated by Django 5.1.6 on 2025-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0009_delete_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkloadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="workload_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
