# Generated by Django 5.1.6 on 2025-05-15 21:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0009_demandeconge_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccrualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('workable_days', models.IntegerField(help_text='Number of workable days in the month (excluding Sundays)')),
                ('days_worked', models.IntegerField(help_text='Number of days actually worked by the employee')),
                ('leave_accrued', models.FloatField(help_text='Leave accrued for this month (in days)')),
                ('is_finalized', models.BooleanField(default=False, help_text="Whether this accrual has been finalized and added to the employee's balance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_accruals', to='conges.employe')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employe', 'month', 'year')},
            },
        ),
    ]
