# Generated by Django 5.1.6 on 2025-02-13 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0010_employeeworkloadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeconge",
            name="employe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employe",
                to="conges.systemeia",
            ),
        ),
    ]
