# Generated by Django 5.1.6 on 2025-02-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0011_alter_demandeconge_employe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeconge",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes",
                to="conges.employe",
            ),
        ),
    ]
