# Generated by Django 5.1.6 on 2025-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0012_alter_demandeconge_employe"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemeia",
            name="charge_travail_predite",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
