# Generated by Django 5.1.6 on 2025-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0013_systemeia_charge_travail_predite"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemeia",
            name="pourcentage_charge_travail",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
