# Generated by Django 5.1.6 on 2025-02-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0014_systemeia_pourcentage_charge_travail"),
    ]

    operations = [
        migrations.RemoveField(model_name="systemeia", name="charge_travail_predite",),
        migrations.RemoveField(
            model_name="systemeia", name="pourcentage_charge_travail",
        ),
    ]
