# Generated by Django 5.1.6 on 2025-02-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0015_remove_systemeia_charge_travail_predite_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="SystemeIA",),
    ]
